### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by harikt** [http-interop/http-middleware#13]
I was looking at  https://github.com/php-fig/container/pull/4 , and it seems the repos under http-interop could explicitly mention that this can move to php-fig and copyright for both.

What do you think ?

As it is MIT for me there is no issue, but was looking at @michaelcullum [comment](https://github.com/php-fig/container/pull/4#issuecomment-241503475).

**Comment by shadowhand** [comment]
The [current license is assigned to FIG](https://github.com/http-interop/http-middleware/blob/4f355b6d3782aaff508d17c176eed52b800dee61/LICENSE#L3).

**Comment by michaelcullum** [comment]
Yep. We'll be getting these repos moved under php-fig soon enough anyway. I just need to sort out logistics with Woody.

**Comment by harikt** [comment]
Great. Looks all is well and can close this issue.

Thank you.
