### ISSUE TITLE
Add the package on Packagist

### ISSUE THREAD

**Issue by mnapoli** [http-interop/http-middleware#14]
I can't find it there at the moment.

**Comment by shadowhand** [comment]
This is blocked by #8.

**Comment by Nyholm** [comment]
Let's add all packages to packagist. Or at least this repo, the factory interfaces and tests.

**Comment by shadowhand** [comment]
https://packagist.org/packages/http-interop/http-middleware

**Comment by shadowhand** [comment]
I've added all the factory packages too.
