### ISSUE TITLE
Bad versioning in release 0.2.1

### ISSUE THREAD

**Issue by mindplay-dk** [http-interop/http-middleware#33]
Release `0.2.1` had a major breaking change, but was tagged as a minor release, breaking our projects this morning.

https://github.com/http-interop/http-middleware/compare/0.2.0...0.2.1

This should have been `0.3`.

We probably should correct by rolling back and releasing as `0.2.2`, then patching and re-releasing the last release as `0.3`.

**Comment by prisis** [comment]
You can remove 0.2.1 and add it again with the readme change, then make a new 0.3 release?

**Comment by shadowhand** [comment]
While BC breaks are allowed in 0.x versions, this was unintentional. I will remove the 0.2.1 tag and tag 0.3.0.
