### ISSUE TITLE
0.2.1 release - packagist

### ISSUE THREAD

**Issue by michalbundyra** [http-interop/http-middleware#36]
Release tag 0.2.1 has been removed in this repository but packagist is not refreshed and this is still there:
https://packagist.org/packages/http-interop/http-middleware#0.2.1

Is it possible to do something with it? In release 0.2.1 interface `MiddlewareInterface` has been removed but  public interface shouldn't be changed in 0.2.X release (BC Break!). This is why now it is tagged as version 0.3.0.

**Comment by shadowhand** [comment]
I just forced a refresh to remove the tag. Thanks for bringing it to our attention!
