### ISSUE TITLE
Namespace and package name

### ISSUE THREAD

**Issue by schnittstabil** [http-interop/http-middleware#38]
According to #34:
> We need to determine how this repo will be transferred to FIG ownership.

Am I right in assuming that, in any case, the namespace will change from `Interop` to `Psr`?

If we don't change our mind, this means:
```
from:
Interop\Http\Middleware\ServerMiddlewareInterface
Interop\Http\Middleware\DelegateInterface

to:
Psr\Http\Middleware\ServerMiddlewareInterface
Psr\Http\Middleware\DelegateInterface
```

And the package name will change
```
from:
http-interop/http-middleware

to:
psr/http-middleware
```

**Comment by shadowhand** [comment]
All of that looks correct. Both packages will probably exist, with `psr/http-middleware` having a [`replace`](https://getcomposer.org/doc/04-schema.md#replace) for `http-interop/http-middleware`.

**Comment by schnittstabil** [comment]
Mhm, thus in any case, the first PSR release (`1.0.0`) can not be backward-compatible – good to know. Thank you.
