### ISSUE TITLE
Delegate interface and dispatcher wording in README.md

### ISSUE THREAD

**Issue by schnittstabil** [http-interop/http-middleware#54]
Form the [current `README.md`](https://github.com/http-interop/http-middleware/tree/cff4fb65317875b2bccbb6b7b22eec18b5a96f04#52-delegate-design)
> ### 5.2 Delegate Design
>
> The `DelegateInterface` defines a single method that accepts a request and
returns a response. **The delegate interface must be implemented by any middleware
dispatcher that uses middleware implementing `ServerMiddlewareInterface`.**

The bold marked part is technically wrong, [`Equip\Dispatch\MiddlewarePipe`](https://github.com/equip/dispatch/blob/c49094c6e485bdde478fdef2e8cd80fd926f9f26/src/MiddlewarePipe.php#L49-L62) is a counter example. Obviously, it is a _middleware dispatcher_ which should not implement the `DelegateInterface`; instead it _creates_ a `DelegateInterface` instance:

```php
class MiddlewarePipe implements ServerMiddlewareInterface
{
    …
    /**
     * Dispatch the middleware stack.
     *
     * @param ServerRequestInterface $request
     * @param callable $default to call when no middleware is available
     *
     * @return ResponseInterface
     */
    public function dispatch(ServerRequestInterface $request, callable $default)
    {
        $delegate = new Delegate($this->middleware, $default);

        return $delegate->process($request);
    }
}
```

**Comment by atanvarno69** [comment]
Would this wording be more correct?
> The delegate interface must be implemented by any middleware dispatching library or package that uses middleware implementing `ServerMiddlewareInterface`.

This describes that `DelegateInterface` must be provided to dispatched middleware without implying that a pipe implementation like `Equip\Dispatch` need implement it directly.

**Comment by schnittstabil** [comment]
@atanvarno69 Well, I believe such a list will never be comprehensive.

Maybe we should just remove the sentence without replacement. Because of the `MiddlewareInterface::process` signature and the [5.1 Middleware Design](https://github.com/http-interop/http-middleware/tree/cff4fb65317875b2bccbb6b7b22eec18b5a96f04#51-middleware-design) paragraph it is already clear that:
* a dispatcher have to provide a `DelegateInterface` instance somehow,
* why such an instance is needed
* and how it is used by a middleware.

**Comment by shadowhand** [comment]
You are free to make your case during the PSR-15 review period. I am calling for the PSR-15 acceptance vote before Jan 17.
