### ISSUE TITLE
ResponseInterface as return type

### ISSUE THREAD

**Issue by cdekok** [http-interop/http-middleware#61]
It would be nice if the interface was bumped to PHP 7 and forces the ResponseInterface as return type in the MiddleWareInterface.

**Comment by shadowhand** [comment]
I agree it would be nice but I think that's a pretty unlikely scenario at this time. I am not entirely sure how the FIG handles versioning, but I wouldn't mind seeing a 1.0.0 that is 5.x compatible, and a 2.0.0 that is 7.x compatible.

**Comment by jschreuder** [comment]
As PHP 5.6 is EOL/security-fixes-only it would be defensible. The PSR would probably only be used in new projects which should target 7.0 anyway.

Could this be decided with a separate vote? As to not endanger passage at all over this.

**Comment by weierophinney** [comment]
We're planning on adding support for this in Stratigility, which supports
PHP 5.6; moving to 7 is not an option for us currently. As such, I'd prefer
not to force that version at this point.

**Comment by akrabat** [comment]
For what it's worth, Slim is also supporting 5.6 and we are not moving to 7 when we introduce support for this.

**Comment by schnittstabil** [comment]
As far as I can see, we only have these options:
1. PSR-15 does not use return type-hinting
    i. and will never do (maybe PSR-51 will do\[*])
    ii. and will do it at v2.0.0
2. PSR-15 use return type-hinting only
3. PSR-15 use return type-hinting and non-return type-hinting (i.e. 4 interfaces: two middleware plus two delegate interfaces)

\[*] within a new namespace of course

– Does anybody see further options?

**Comment by damianopetrungaro** [comment]
The versioning topic has been discussed in FIG Mailing list.
No BC will be provided for this kind of update.

**Comment by shadowhand** [comment]
The PSR version of these interfaces could target PHP7 exclusively. I'm not strictly opposed, except that PHP 5.6 is not *yet* EOL and even when it is, there will be a fair number of people that continue to use it. (Hopefully not too many.)

Regardless, this debate should be had on the FIG mailing list, not here.
