### ISSUE TITLE
Delegates which are not defined within middleware dispatching systems!?

### ISSUE THREAD

**Issue by schnittstabil** [http-interop/http-middleware#62]
> #### Why does the delegate conflict with middleware?
> …
> The implementation of delegate should be defined within middleware dispatching systems.

I've reread this sentence multiple times from different points of view and I'm asking myself:

> Is it anyhow possible that a delegate is **not** defined within middleware dispatching system?

I mean, if `$d instanceof DelegateInterface`, then `$d` can be used to dispatch middlewares, thus `$d` is part of the middleware dispatching system, isn't it?

_Note:_ I must admit, the word _within_ above does not make much sense to me in a [packagist.org](https://packagist.org/) world.

**Comment by shadowhand** [comment]
No longer a concern with #71.
