### ISSUE TITLE
Clarification of Misuse is Missing

### ISSUE THREAD

**Issue by schnittstabil** [http-interop/http-middleware#66]
**Note:** Section 5.2 was updated and clarified a bit, which made discussions at #63 obsolet.

[Current version](https://github.com/php-fig/fig-standards/blob/936a346bdeec7ef62f5da873a8a2ea1ff96b2989/proposed/http-middleware/middleware-meta.md#why-does-the-delegate-conflict-with-middleware):

> ### 5.2 Delegate Design
> #### Why does the delegate conflict with middleware?
> Both the middleware and delegate interface define a `process` method to discourage misuse of middleware as delegates.

As seen at #63, we cannot prevent that _misuse_ just by naming both methods `process`:

```php
class BottomMiddleware implements DelegateInterface, MiddlewareInterface
{
    function process(ServerRequestInterface $request, DelegateInterface $delegate = null)
    {
        return new Response();
    }
}
```

(https://3v4l.org/rgtcR proves that PHP allows that)

As a reader, I still don't know WHY it would be a misuse. And according to @crell's [comment at the mailing list](https://groups.google.com/forum/#!topic/php-fig/HD5meon7TX0), I believe I'm not alone. Above is a _bottom middleware_ and clearly does not violate SRP, moreover as far as I can see it is a counter example of any _misuse_ I can think of.

**Hence, I believe it's worth to add an explanation what kind of _misuse_ we are talking about to the metadoc.**

**Comment by shadowhand** [comment]
With the changes in #71 this is no longer an issue.
