### ISSUE TITLE
Rename package?

### ISSUE THREAD

**Issue by shadowhand** [http-interop/http-middleware#76]
With the changes made in #75, the package name `http-middleware` no longer makes sense. Is it time to rename this repo and package to `http-request-handlers`, perhaps even `psr/http-request-handlers` to prepare for the eventual adoption by FIG?

**Comment by weierophinney** [comment]
Doing so might make it easier for some of us trying to support multiple versions of the package, as we could target both the old and the new namespaces more easily (arguably, this would have been useful for the 0.5.0 release as well).

That said, I'd do it as a separate repository. That way the original packages can still be downloaded and found by existing URIs, and new packages have the new package name and associated repository URI.

**Comment by shadowhand** [comment]
https://github.com/http-interop/http-request-handlers has been created, with changes from #75 applied. And http-interop/http-request-handlers#1 changes to `psr` namespace for code and package.
