### ISSUE TITLE
1.1.0 seems to be broken

### ISSUE THREAD

**Issue by shadowhand** [http-interop/http-middleware#79]
Please see these tests:
https://travis-ci.org/zendframework/zend-stratigility/jobs/332049603#L644

So the problem is only on the latest release. It's because the interface extends PSR-15 interface and method defined in the PSR-15 interface typehint against PST-15 interface, not as before interop interface. Basically 1.1.0 has a BC Break...

Refs http-interop/http-server-handler#12 by @webimpress

**Comment by michalbundyra** [comment]
@shadowhand hm... wait ... wrong repo again it should be https://github.com/http-interop/http-server-middleware

**Comment by shadowhand** [comment]
@webimpress yes. :(
